# Generated by Django 2.2 on 2019-07-13 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=30, unique=True, verbose_name='账号')),
                ('nickname', models.CharField(default='', max_length=45, verbose_name='昵称')),
                ('email', models.CharField(default='', max_length=45, unique=True, verbose_name='邮箱')),
                ('mobile', models.CharField(default='', max_length=11, unique=True, verbose_name='手机号')),
                ('pwd', models.CharField(max_length=32, verbose_name='密码')),
                ('login_num', models.PositiveIntegerField(default=0, verbose_name='登录次数')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后一次登录时间')),
                ('login_ip', models.CharField(max_length=15, verbose_name='ipv4地址')),
                ('state', models.BooleanField(default=True, verbose_name='状态，1禁用 0正常')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': '管理员表',
            },
        ),
        migrations.CreateModel(
            name='Admin_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='操作类型')),
                ('title', models.CharField(max_length=150, verbose_name='操作日志标题')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('user_agent', models.CharField(max_length=240, verbose_name='记录用户客户端信息')),
                ('referer', models.CharField(max_length=100, verbose_name='操作来源页')),
                ('ip', models.CharField(max_length=15, verbose_name='ip')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='putao.Admin', verbose_name='管理员模型的外键')),
            ],
        ),
    ]
