# Generated by Django 2.2 on 2019-06-25 05:56

import app04.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='作者名称')),
                ('email', models.EmailField(default='', max_length=50)),
                ('number_id', app04.models.MyField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('press_name', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('books_name', models.CharField(max_length=25)),
                ('publish_date', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.PositiveSmallIntegerField(default=50)),
                ('sales_num', models.PositiveIntegerField(default=0)),
                ('us_shelf', models.BooleanField(default=False)),
                ('press', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pb', to='app04.Press')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Author2Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app04.Author')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app04.Books')),
            ],
            options={
                'unique_together': {('books', 'author')},
            },
        ),
        migrations.AddField(
            model_name='author',
            name='bookss',
            field=models.ManyToManyField(through='app04.Author2Books', to='app04.Books'),
        ),
    ]
