# Generated by Django 2.2 on 2019-06-25 06:47

import app01.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('press_name', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('books_name', models.CharField(max_length=25)),
                ('publish_date', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.PositiveSmallIntegerField(default=50)),
                ('sales_num', models.PositiveIntegerField(default=0)),
                ('us_shelf', models.BooleanField(default=False)),
                ('press', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pb', to='app01.Press')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(default='', max_length=50)),
                ('number_id', app01.models.MyField(max_length=18)),
                ('bookss', models.ManyToManyField(to='app01.Books')),
            ],
        ),
    ]
