# Generated by Django 2.2 on 2019-06-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
