# Generated by Django 2.2 on 2019-06-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_books_sales_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='us_shelf',
            field=models.BooleanField(default=False),
        ),
    ]
