# Generated by Django 2.2 on 2019-06-21 06:05

import app02.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0006_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='number_id',
            field=app02.models.MyField(default='', max_length=18),
            preserve_default=False,
        ),
    ]
