# Generated by Django 2.2 on 2019-06-21 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=120)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('click', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Articles_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app03.Articles')),
            ],
        ),
    ]
