# Generated by Django 2.2 on 2019-05-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_name',
            new_name='student_names',
        ),
    ]
