# Generated by Django 2.2 on 2019-05-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190531_0622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
