# Generated by Django 2.2 on 2019-06-03 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190603_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='press',
            old_name='press_names',
            new_name='press_name',
        ),
    ]
