# Generated by Django 2.2 on 2019-06-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_books_press'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
    ]
