# Generated by Django 2.2 on 2019-06-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('books_name', models.CharField(max_length=25)),
            ],
        ),
    ]
