# Generated by Django 2.2 on 2019-06-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('press_name', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('books_name', models.CharField(max_length=25)),
                ('press', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app02.Press')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('bookss', models.ManyToManyField(to='app02.Books')),
            ],
        ),
    ]
