# Generated by Django 2.2 on 2019-07-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190704_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': (['-id'],), 'verbose_name': '管理员表'},
        ),
    ]
