# Generated by Django 2.2 on 2019-07-05 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20190705_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 6, 51, 561312), verbose_name='最后一次登录时间'),
        ),
        migrations.AlterField(
            model_name='admin_log',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 6, 51, 562042), verbose_name='操作时间'),
        ),
    ]
