# Generated by Django 2.2 on 2019-07-05 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190705_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后一次登录时间'),
        ),
        migrations.AlterField(
            model_name='admin_log',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间'),
        ),
    ]
