# Generated by Django 2.2 on 2019-07-06 15:32

from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20190706_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('tags', models.CharField(default='', max_length=50, verbose_name='标签')),
                ('describles', models.CharField(max_length=200, verbose_name='描述')),
                ('pic', models.ImageField(upload_to='static/upload/article/%Y%m%d/', verbose_name='图片')),
                ('flag', manager.models.CustomeTinyIntField(default=0, max_length=1, verbose_name='文章推荐 0默认 1置顶 2 推荐')),
                ('add_time', manager.models.CustomeTimeStampField(verbose_name='添加时间')),
                ('click', models.PositiveIntegerField(default=0, verbose_name='点击量')),
                ('support', models.PositiveIntegerField(default=0, verbose_name='点赞')),
                ('seo_title', models.CharField(max_length=50, verbose_name='seo标题')),
                ('seo_keyword', models.CharField(max_length=60, verbose_name='seo关键词')),
                ('seo_description', models.CharField(max_length=200, verbose_name='seo描述')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Admin', verbose_name='添加人')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.ImageField(default='', max_length=150, upload_to='static/upload/%Y%m%d/', verbose_name='栏目图片'),
        ),
        migrations.CreateModel(
            name='Atricle_additional',
            fields=[
                ('article', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manager.Article')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Category', verbose_name='栏目id'),
        ),
    ]
