# Generated by Django 2.2 on 2019-07-08 17:20

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20190706_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=manager.models.CustomeTimeStampField(default='2019-07-08 17:20:16', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.CharField(default='', max_length=200, verbose_name='图片'),
        ),
    ]
