# Generated by Django 2.2 on 2019-07-09 15:31

from django.db import migrations
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20190709_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='weight',
        ),
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=manager.models.CustomeTimeStampField(default='2019-07-09 15:31:10', verbose_name='添加时间'),
        ),
    ]
