# Generated by Django 2.2 on 2019-07-09 16:23

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20190709_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=manager.models.CustomeTimeStampField(default='2019-07-09 16:23:12', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.ImageField(default='', max_length=150, upload_to='uploads/%Y%m%d/', verbose_name='栏目图片'),
        ),
    ]
