# Generated by Django 2.2 on 2019-07-09 16:53

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20190709_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='nickname',
            field=models.CharField(default='', max_length=45, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=manager.models.CustomeTimeStampField(default='2019-07-09 16:53:09', verbose_name='添加时间'),
        ),
    ]
