# Generated by Django 2.2 on 2019-06-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='press',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('press_name', models.CharField(max_length=35, unique=True)),
            ],
        ),
    ]
