# Generated by Django 2.2 on 2019-06-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='press',
            old_name='press_name',
            new_name='press_names',
        ),
    ]
