# Generated by Django 2.2 on 2019-06-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='books',
        ),
    ]
