# Generated by Django 2.2 on 2019-06-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20190603_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_name',
            new_name='books_name',
        ),
    ]
